# Generated by Django 4.2.6 on 2023-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(default='None'),
        ),
    ]
